services:
  - type: web
    name: fintech-backend
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: PORT
        value: 10000
      - key: MONGO_URI
        value: ${MONGO_URI}
